version: '3.7'

services:
  espress_pdf:
    container_name: express-pdf
    image: express-pdf:1.0.0
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3330:3330
    volumes:
      - .:/src/
      - node_modules:/src/node_modules 
    command: npm run start
    restart: unless-stopped

volumes:
  node_modules:
    name: espress_pdf-node_modules